### PR TITLE
Fix ROF code.

### PR DESCRIPTION
**Pull request by nico**
The Chambolle paper this is based on --
http://www.cmap.polytechnique.fr/preprint/repository/578.pdf --
initializes Xi_0 with 0, not with g (see page 13 at the bottom).

Consider this code:

```
im = misc.lena()
U, T = rof.denoise(im, im, tv_weight=30)
imshow(U)
```

Before this change, this produced the output
http://i.imgur.com/u68Vakj.jpg . With this change, it produces
http://i.imgur.com/3eHli7J.jpg which looks more correct.

### CODE REVIEW

**Comment by jesolem** [comment]
Great catch. I will take the change for the file in PCV/tools but not the book copy folder (that might confuse some readers). Thanks!

**Comment by jesolem** [comment]
Thanks for this!

I will take the change for the file in PCV/tools but prefer to leave the
book copy folder unchanged until a second edition.

I'd like to give you credit so if you change the pull request to just the
one file, I'll accept it.

**Comment by nico** [comment]
Do you want me to completely revert the change to the book copy, or should I add some kind of comment ("# This is what's printed in the book, but see PCV/tools for an improved version" or something)?

**Comment by jesolem** [comment]
On second thought, I'll take it as is and for now add a comment that the two lines were changed from what's in the book.

**Comment by nico** [comment]
Thanks!

**Pull request merged**
